# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

image:
  registry: ""
  repository: atomix/consensus-controller
  tag: v0.7.0
  pullPolicy: ""
  pullSecrets: []

node:
  image:
    registry: ""
    repository: atomix/consensus-node
    tag: v0.13
    pullPolicy: ""
    pullSecrets: []
